version: "3.4"

services:
  app:
    image: "registry.sostoya.com/smart_home:0.0.1"
    expose:
      - 3000
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.smarthome.rule=Host(`iot.mtdl.ru`)"
      - "traefik.http.routers.smarthome.entrypoints=web,secure"
      - "traefik.http.routers.smarthome.tls.certresolver=ssl"
networks:
  proxy:
    external: true
