version: "3.4"

services:
  app:
    image: "registry.sostoya.com/smart_home:0.0.3"
    expose:
      - 3000
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.smarthome.rule=Host(`iot.mtdl.ru`)"
      - "traefik.http.routers.smarthome.entrypoints=secure"
      - "traefik.http.routers.smarthome.tls.certresolver=ssl"
  broker:
    image: eclipse-mosquitto
    expose:
      - 1883
    networks:
      - proxy
    volumes:
      - smarthome_broker:/mosquitto/config
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.smarthome_broker.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.smarthome_broker.entrypoints=mqtt"
networks:
  proxy:
    external: true

volumes:
  smarthome_broker:
