version: "3.4"

services:
  app:
    image: "registry.sostoya.com/smart_home:0.0.2"
    expose:
      - 3000
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.smarthome.rule=Host(`iot.mtdl.ru`)"
      - "traefik.http.routers.smarthome.entrypoints=secure"
      - "traefik.http.routers.smarthome.tls.certresolver=ssl"

      - "traefik.http.routers.smarthome_events.rule=Host(`iot.mtdl.ru`) && PathPrefix(`/events`)"
      - "traefik.http.routers.smarthome_events.entrypoints=web"
networks:
  proxy:
    external: true
