export enum ColorScene {
  ALARM = 'alarm',
  ALICE = 'alice',
  CANDLE = 'candle',
  DINNER = 'dinner',
  FANTASY = 'fantasy',
  GARLAND = 'garland',
  JUNGLE = 'jungle',
  MOVIE = 'movie',
  NEON = 'neon',
  NIGHT = 'night',
  OCEAN = 'ocean',
  PARTY = 'party',
  READING = 'reading',
  REST = 'rest',
  ROMANCE = 'romance',
  SIREN = 'siren',
  SUNRISE = 'sunrise',
  SUNSET = 'sunset',
}
