export enum ModeValue {
  AUTO = 'auto',
  ECO = 'eco',
  TURBO = 'turbo',
  COOL = 'cool',
  DRY = 'dry',
  FAN_ONLY = 'fan_only',
  HEAT = 'heat',
  PREHEAT = 'preheat',
  HIGH = 'high',
  LOW = 'low',
  MEDIUM = 'medium',
  MAX = 'max',
  MIN = 'min',
  FAST = 'fast',
  SLOW = 'slow',
  EXPRESS = 'express',
  NORMAL = 'normal',
  QUIET = 'quiet',
  HORIZONTAL = 'horizontal',
  STATIONARY = 'stationary',
  VERTICAL = 'vertical',
  ONE = 'one',
  TWO = 'two',
  THREE = 'three',
  FOUR = 'four',
  FIVE = 'five',
  SIX = 'six',
  SEVEN = 'seven',
  EIGHT = 'eight',
  NINE = 'nine',
  TEN = 'ten',

  //TODO Add the rest
}
